openapi: 3.0.2
info:
  title: PRcard API
  description: |-
    <b>6種の北海道チーズ牛丼 サーバサイド API仕様</b>
  version: 1.0.0
servers:
  - url: http://localhost:8080/
tags:
  - name: auth
    description: 認証API
  - name: PRCard
    description: PRカード関連API
  - name: QR
    description: QRカード関連API
  - name: Twitter
    description: Twitter関連API
  - name: Github
    description: Github関連API

paths:
  /auth:
    post:
      tags:
        - auth
      summary: ユーザアカウント認証情報作成API
      description: |-
        ユーザの認証情報を作成します。
        ユーザの名前情報をリクエストで受け取り、サーバ内だけで利用するIDと認証用のトークンを生成しデータベースへ保存します。
      requestBody:
        description: Request Body
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthCreateRequest'
        required: true
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthCreateResponse'
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /card:
    post:
      tags:
        - PRCard
      summary: PRカード情報入力API
      description: |-
        名前・サムネイル・自己紹介文・レーダーチャート用の項目と数値をパラメーターにして、名刺画像生成してを200を返却。
      security:
        - ApiToken: []
      requestBody:
        description: Request Body
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PRCardRequest'
        required: true
      responses:
        200:
          description: OK
          content: {}
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    put:
      tags:
        - PRCard
      summary: PRカード情報更新API
      description: |-
        名前・サムネイル・自己紹介文・レーダーチャート用の項目と数値をパラメーターにして、名刺画像生成してを200を返却。
      security:
        - ApiToken: []
      requestBody:
        description: Request Body
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PRPutRequest'
        required: true
      responses:
        200:
          description: OK
          content: {}
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    get:
      tags:
        - PRCard
      summary: PRカード取得API
      description: |-
        名刺情報入力APIで取得した情報を用いて作成した画像を返却。
      security:
        - ApiToken: []
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PRCardResponse'
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  '/card/{user_id}':
    get:
      tags:
        - PRCard
      summary: 他ユーザのカード情報を取得
      description: |-
        ユーザ情報の更新をします。
        初期実装では名前の更新を行います。
      security:
        - ApiToken: []
      parameters:
        - $ref: '#/components/parameters/UserID'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PRCardResponse'
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /card/all:
    get:
      tags:
        - PRCard
      summary: PRカード画像一覧取得API
      description: |-
        全ユーザのPRカードを取得するAPI。
      security:
        - ApiToken: []
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SkillListResponse'
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /card/2:
    post:
      tags:
        - PRCard
      summary: PRカード情報入力API2
      description: |-
        PRカード作成に必要なデータをパラメータにして名刺画像を取得して200を返却。
      security:
        - ApiToken: []
      requestBody:
        description: Request Body
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ItemsResponse'
        required: true
      responses:
        200:
          description: OK
          content: {}
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /qr:
    get:
      tags:
        - QR
      summary: ユーザーのQRコード取得API
      description: |-
        ユーザのQRコードを返却します。
        required: true
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QRRespnse'
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    AuthCreateRequest:
      type: object
      properties:
        userId:
          type: string
          description: ユーザーID
        password:
          type: string
          description: パスワード
      required:
        - userId
        - password
    AuthCreateResponse:
      type: object
      properties:
        token:
          type: string
          description: クライアント側で保存するトークン
        uuid:
          type: string
          description: 自動ログイン用のuuid
      required:
        - token
    PRCardRequest:
      type: object
      properties:
        name:
          type: string
          description: 名前
          example: たかし
        thumbnail:
          type: string
          description: アイコン
          example: "ljkfalkjflkjaflsekjfldjlkj"
        items:
          type: object
          description: レーダーチャート用のデータ
          $ref: '#/components/schemas/ItemsResponse'
    ItemsResponse:
      type: object
      properties:
        items1:
          type: integer
          example: 100
        items2:
          type: integer
          example: 100
        items3:
          type: integer
          example: 100
        items4:
          type: integer
          example: 100
        items5:
          type: integer
          example: 100
    PRCardResponse:
      properties:
        prcard:
          type: string
          description: PRカード
          example: "kjkaiojdiosgjoakojkg"
    SkillListResponse:
      type: array
      items:
        $ref: '#/components/schemas/PRCardResponse'
    PRPutRequest:
      type: array
      items:
        $ref: '#/components/schemas/ItemsResponse'
    QRRespnse:
      properties:
        qr:
          type: string
          description: qrコード
          example: "kjkaiojdiosgjoakojkg"
    ErrorResponse:
      type: object
      properties:
        code:
          type: integer
          description: ステータスコード
        message:
          type: string
          description: エラーメッセージ
      required:
        - code
        - message
  parameters:
    UserID:
      name: user_id
      in: path
      required: true
      description: userID
      schema:
        type: integer
  securitySchemes:
    ApiToken:
      type: apiKey
      in: header
      name: X-API-TOKEN
